Fixed tabs

diff --git a/ee4-backup-sites b/ee4-backup-sites
--- a/ee4-backup-sites
+++ b/ee4-backup-sites
@@ -4,18 +4,18 @@
 
 main() {
 
-    # Load Configuration
-    if [[ -r ~/.ee4-backup-settings.conf ]] ; then
-        . ~/.ee4-backup-settings.conf
-    else
-        echo "ERROR - Settings file not found or not readable."; exit 1
-    fi
+	# Load Configuration
+	if [[ -r ~/.ee4-backup-settings.conf ]] ; then
+		. ~/.ee4-backup-settings.conf
+	else
+		echo "ERROR - Settings file not found or not readable."; exit 1
+	fi
 
 	## Prepare automated restore list - Coming Soon
 	#echo "Preparing automated restore list"
 	#rlfilename=/tmp/restorelist-`/bin/date -u +"%Y%m%dT%H%M%SZ"`.txt
-    #/root/restorelist > $rlfilename
-    #aws s3 cp $rlfilename s3://$bucket/$config_base_folder/restorelist/
+	#/root/restorelist > $rlfilename
+	#aws s3 cp $rlfilename s3://$bucket/$config_base_folder/restorelist/
 	#rm $rlfilename
 
 	## Backup LetsEncrypt certs - Coming Soon
@@ -30,7 +30,7 @@ main() {
 	do
 		echo Working on: $domain
 
-        ## Backup Database
+		## Backup Database
 		dbfilename=$domain-`/bin/date -u +"%Y%m%dT%H%M%SZ"`.sql
 		tmp=/tmp
 		db_user=`ee site info $domain | grep 'DB User' | awk -F '|' '{print $3}' | awk '{print $1}'`
@@ -61,14 +61,14 @@ main() {
 		## Cleanup
 		rm $tmp/$filename*
 
-        ## Move site access logs to S3
-        if ls /opt/easyengine/sites/$domain/logs/nginx/access* > /dev/null 2>&1; then
-		 	logfilename=$domain-access-`/bin/date -u +"%Y%m%dT%H%M%SZ"`.log
-            mv /opt/easyengine/sites/$domain/logs/nginx/access.log /opt/easyengine/sites/$domain/logs/nginx/$logfilename
+		## Move site access logs to S3
+		if ls /opt/easyengine/sites/$domain/logs/nginx/access* > /dev/null 2>&1; then
+			logfilename=$domain-access-`/bin/date -u +"%Y%m%dT%H%M%SZ"`.log
+			mv /opt/easyengine/sites/$domain/logs/nginx/access.log /opt/easyengine/sites/$domain/logs/nginx/$logfilename
 			nice -n 19 gzip /opt/easyengine/sites/$domain/logs/nginx/$logfilename
 			aws s3 mv $s3options /opt/easyengine/sites/$domain/logs/nginx/$logfilename.gz s3://$bucket/$log_base_folder/$domain/
 			aws s3 ls s3://$bucket/$log_base_folder/$domain/$logfilename.gz
-        fi
+		fi
 	done
 }
 
